
import "./globals.css";
import {StateProvider} from "../context/ItemProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased  sm:w-[80%] sm:mx-auto mt-20 sm:container ">
      <StateProvider>{children}
      <Toaster />
      </StateProvider>
        
      </body>
    </html>
  );
}
